# Generated by Django 4.2.1 on 2023-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200)),
                ('Lastname', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Category', models.CharField(choices=[('student_radio', 'Student'), ('pro_radio', 'Professional'), ('content_radio', 'Content Creator'), ('consult_radio', 'Strategy & consulting'), ('business_radio', 'Business Owner'), ('gov_radio', 'Government/ Public Service'), ('other_radio', 'Other')], default='other_radio', max_length=20)),
            ],
        ),
    ]
